version: '3.8'

services:
  bdi:
    build: .
    container_name: bdi_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
